//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelsCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelsCar()
        {
            this.CompanyFleets = new HashSet<CompanyFleet>();
        }
    
        public int Id { get; set; }
        public int ManufacturerId { get; set; }
        public string Model { get; set; }
        public decimal PricePerDay { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFleet> CompanyFleets { get; set; }
        public virtual ManufacturersCar ManufacturersCar { get; set; }
    }
}
