//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal TotalCost { get; set; }
        public string Photo { get; set; }
        public string Model { get; set; }
        public string ManufacturerName { get; set; }
        public int UserId { get; set; }
    }
}
